version: '3.8'

services:
  app:
    build: .
    container_name: tron-exchange-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    volumes:
      - ./logs:/app/logs
    networks:
      - tron-exchange-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: tron-exchange-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - tron-exchange-network
    depends_on:
      - app

networks:
  tron-exchange-network:
    driver: bridge 